name = LIA Arduino
version = 1.0.0
author = Gael, Jael & Baltman
maintainer = theBaltman04 <bzamudio208@uvaq.edu.mx>
sentence = Libreria Invernadero Automatizado -LIA-
paragraph = Libreria de arquitectura POO para el control de invernaderos inteligentes con MCU(Arduino)
category = Device Control
url =  https://github.com/jaelurbina10/LIA-ESP32.git
architectures = *